Day2_Helpers/Day2_Helpers/Models/BookModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Day2_Helpers.Models
{
    public class BookModel
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public int TotalPages { get; set; }
        public string Description { get; set; }
        public List<string> Booktype { get; set; }
    }
}

Day2_Helpers/Day2_Helpers/Models/ErrorViewModel.cs
using System;

namespace Day2_Helpers.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day2_Helpers/Day2_Helpers/Models/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Day2_Helpers.Models
{
    public class Register
    {
        [Required(ErrorMessage ="Please Enter your Name ")]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Compare("Password",ErrorMessage ="Password and Confirm password does not match")]
        public string ConfirmPassword { get; set; }
        public float Salary { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name="Email Address")]
        public string Email { get; set; }
        public string Address { get; set; }


    }
}

Day2_Helpers/Day2_Helpers/Controllers/HomeController.cs
using Day2_Helpers.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Day2_Helpers.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day2_Helpers/Day2_Helpers/Controllers/HtmlHelperController.cs
using Day2_Helpers.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Day2_Helpers.Controllers
{
    public class HtmlHelperController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //Standard html helper
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Register register)
        {
            return View();
        }

        //Scaffolded code  //Tag helper
        public IActionResult RForm()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RForm(Register register)
        {
            //Checks for all the validation is satisfied or not
            if(ModelState.IsValid)
            {

            }
            else
            {

            }
            return View();
        }

    }
}

Day2_Helpers/Day2_Helpers/Controllers/TagHelperController.cs
using Day2_Helpers.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Day2_Helpers.Controllers
{
    public class TagHelperController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //by default all the action methods are get method
        public IActionResult AddBook()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBook(BookModel book)
        {
            List<BookModel> b = new List<BookModel>();
            b.Add(book);
            return View("DisplayBookDetails",b);
        }

        public IActionResult DisplayBookDetails(BookModel book)
        {
            return View(book);
        }
    }
}

Day2_Helpers/Day2_Helpers/Views/HtmlHelper/Create.cshtml
@model Register
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
@using(Html.BeginForm())
            {
<table border="1" cellspacing="5" cellpadding="5">
    <tr>
        <td>@Html.Label("Enter your Name")</td>
        <td>@Html.TextBox("Name")</td>
    </tr>
    <tr>
        <td>@Html.Label("Enter your Password")</td>
        <td>@Html.Password("txtpwd")</td>
    </tr>
    <tr>
        <td>@Html.Label("Enter your Salary")</td>
        <td>@Html.TextBox("txtsalary")</td>
    </tr>

    <tr>
        <td>@Html.Label("Enter your Address")</td>
        <td>@Html.TextBox("txtaddress")</td>
    </tr>

</table>
<input type="submit" value="save" />
            }

Day2_Helpers/Day2_Helpers/Views/HtmlHelper/RForm.cshtml
@model Day2_Helpers.Models.Register

@{
    ViewData["Title"] = "RForm";
}

<h1>RForm</h1>

<h4>Register</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Day2_Helpers/Day2_Helpers/Views/TagHelper/AddBook.cshtml
@model BookModel
@{
    ViewData["Title"] = "AddBook";
}

<h1>AddBook</h1>

<a asp-action="Index" asp-controller="Home">Go to Index </a>
<form method="post" asp-action="AddBook" asp-controller="TagHelper">
    <div>
        <label asp-for="BookId"></label>
        <input asp-for="BookId" />
    </div>
    <div>
        <label asp-for="BookName"></label>
        <input asp-for="BookName" />
    </div>
    <div>
        <label asp-for="AuthorName"></label>
        <input asp-for="AuthorName" />
    </div>
    <div>
        <label asp-for="TotalPages"></label>
        <input asp-for="TotalPages" />
    </div>
    <div>
        <label asp-for="Description"></label>
        <textarea asp-for="Description" cols="30" rows="6"></textarea>
    </div>
    <div>
        <label asp-for="Booktype"></label>
        <select>
            <option value="C">Comic</option>
            <option value="A">Action</option>
        </select>
    </div>
    <div>
        <input type="submit" value="Add Book" class="btn btn-dark" />
    </div>
</form>

Day2_Helpers/Day2_Helpers/Views/TagHelper/DisplayBookDetails.cshtml
@model IEnumerable<Day2_Helpers.Models.BookModel>
@{
    ViewData["Title"] = "DisplayBookDetails";
}

<h1>DisplayBookDetails</h1>

@foreach(var item in Model)
            {
                <li>@item.BookName</li>
                <li>@item.Description</li>
            }